---
- name: Create a specific user on all web servers
  hosts: webservers
  become: yes
  vars:
    username: webuser
  tasks:
#    - name: Create the 'webuser' account
    - name: Create the '{{ username }}' account
      user:
#        name: webuser
       name: "{{ username }}"
       password: "{{ password | password_hash('sha512') }}"
       update_password: always
       state: present
